In [1]:
import pandas as pd #step1: Load the dataset using Pandas.

In [2]:
data=pd.read_csv("/content/diabetes.csv")

In [3]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [5]:
#step2: explore dataset
data.shape

(768, 9)

In [6]:
data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [18]:
data.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [19]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [13]:
#step3: separate features and target
x=data.drop("Outcome", axis=1)
y=data["Outcome"]

In [21]:
x.shape

(768, 8)

In [22]:
y.shape

(768,)

In [11]:
x.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [12]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [15]:
#step4: train the test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [16]:
x_train.shape

(576, 8)

In [17]:
x_test.shape

(192, 8)

In [20]:
#step5 : feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [27]:
# Part 2 - Building the Artifical Neural Network (ANN)

import tensorflow as tf
from tensorflow import keras #one of the most important modules within Tensorflow
from tensorflow.keras import layers #layers will help us in developing the neural network layers

In [28]:
#step3: Add the Layers

#building the NN using Tensorflow and Keras - we build it like a Sequential Model with layers stacked on top of each other
model=keras.Sequential([
    layers.Input(shape=(x_train.shape[1],),name='input_layer'), #input_layer has 8 neurons
    layers.Dense(16,activation='relu',name='hidden_layer_1'), #hidden_layer_1 has 16 neurons
    layers.Dense(32,activation='relu',name='hidden_layer_2'), #hidden_layer_2 has 32 neurons
    layers.Dense(1,activation='sigmoid',name='output_layer') #output_layer has just 1 neuron since it is a binary classifier
])

In [29]:
#step4: Activation Functions

model.compile(
    optimizer='adam', #optimizer will ensure that the gradient loss is within the range
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [38]:
model.fit(x_train,y_train,epochs=20,batch_size=32)

Epoch 1/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7656 - loss: 0.4840
Epoch 2/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7691 - loss: 0.4801
Epoch 3/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7656 - loss: 0.4770
Epoch 4/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7656 - loss: 0.4730
Epoch 5/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7674 - loss: 0.4708
Epoch 6/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7622 - loss: 0.4683
Epoch 7/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7674 - loss: 0.4667
Epoch 8/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7691 - loss: 0.4640
Epoch 9/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7656 - loss: 0.4622
Epoch 10/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7639 - loss: 0.4594
Epoch 11/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7639 - loss: 0.4576
Epoch 12/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7726 - loss: 0.4559
Epoch 13/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7708 - loss: 0.4546
Epoch 14/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7726 - loss: 0.4534
Epoch 15/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7760 - loss: 0.4519
Epoch 16/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7708 - loss: 0.4524
Epoch 17/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7726 - loss: 0.4490
Epoch 18/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7760 - loss: 0.4482
Epoch 19/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7795 - loss: 0.4469
Epoch 20/20
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7778 - loss: 0.4454

In [39]:
y_pred=model.predict(x_test)
print(y_pred)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
[[0.5203986 ]
 [0.12232511]
 [0.05097097]
 [0.2336433 ]
 [0.12785992]
 [0.83047605]
 [0.35946646]
 [0.26451406]
 [0.03519187]
 [0.09016263]
 [0.30776218]
 [0.19173804]
 [0.17881273]
 [0.7214062 ]
 [0.08572614]
 [0.599603  ]
 [0.7052111 ]
 [0.35214275]
 [0.29093376]
 [0.30682024]
 [0.6540349 ]
 [0.79876155]
 [0.26510015]
 [0.3330293 ]
 [0.83875746]
 [0.10547614]
 [0.7136704 ]
 [0.2790901 ]
 [0.6472157 ]
 [0.62722355]
 [0.48989147]
 [0.17876023]
 [0.05585845]
 [0.06982045]
 [0.24221584]
 [0.10205816]
 [0.8348961 ]
 [0.7831125 ]
 [0.02873109]
 [0.3849533 ]
 [0.48754185]
 [0.84122664]
 [0.15383734]
 [0.67116016]
 [0.0317385 ]
 [0.8572752 ]
 [0.13650762]
 [0.18021081]
 [0.16268711]
 [0.00198431]
 [0.29574966]
 [0.68353885]
 [0.7506708 ]
 [0.02547171]
 [0.72117186]
 [0.3186847 ]
 [0.27644813]
 [0.02554994]
 [0.32355413]
 [0.76268274]
 [0.84607065]
 [0.12572375]
 [0.84817356]
 [0.03514395]
 [0.8061138 ]
 [0.1497167 ]
 [0.746389  ]
 [0.7462166 ]
 [0.1154367 ]
 [0.20808184]
 [0.7048248 ]
 [0.10204213]
 [0.2412586 ]
 [0.4005995 ]
 [0.13469812]
 [0.30862644]
 [0.08924457]
 [0.5127288 ]
 [0.864799  ]
 [0.8433933 ]
 [0.41767684]
 [0.5035522 ]
 [0.13442647]
 [0.27926674]
 [0.38112107]
 [0.8408478 ]
 [0.13528554]
 [0.09779319]
 [0.06713989]
 [0.795741  ]
 [0.75266266]
 [0.4491721 ]
 [0.3648214 ]
 [0.5411215 ]
 [0.54221636]
 [0.1874648 ]
 [0.25935078]
 [0.9412976 ]
 [0.05328612]
 [0.47480103]
 [0.7784297 ]
 [0.5021306 ]
 [0.7771642 ]
 [0.65500546]
 [0.02245978]
 [0.17769812]
 [0.05489279]
 [0.26851067]
 [0.845695  ]
 [0.19487804]
 [0.79208004]
 [0.01942788]
 [0.65266275]
 [0.04591   ]
 [0.36456925]
 [0.8491771 ]
 [0.10079022]
 [0.03508862]
 [0.04144843]
 [0.93649286]
 [0.05807793]
 [0.13149834]
 [0.14164706]
 [0.03956075]
 [0.12440266]
 [0.11196214]
 [0.59803   ]
 [0.7765226 ]
 [0.25354302]
 [0.8802494 ]
 [0.0425578 ]
 [0.05487719]
 [0.00780797]
 [0.11302231]
 [0.02152815]
 [0.02228129]
 [0.6644948 ]
 [0.25646082]
 [0.24849728]
 [0.7948222 ]
 [0.3023085 ]
 [0.02672059]
 [0.6115493 ]
 [0.139064  ]
 [0.17473939]
 [0.33895016]
 [0.5134844 ]
 [0.1539443 ]
 [0.16590823]
 [0.91065586]
 [0.8431392 ]
 [0.0696535 ]
 [0.08995599]
 [0.01217997]
 [0.7508667 ]
 [0.05260631]
 [0.7244869 ]
 [0.4184242 ]
 [0.04874632]
 [0.30579826]
 [0.18396667]
 [0.97751683]
 [0.02734546]
 [0.0401157 ]
 [0.53904825]
 [0.36872336]
 [0.18028267]
 [0.6252296 ]
 [0.9332187 ]
 [0.12742047]
 [0.5959424 ]
 [0.9049366 ]
 [0.35847834]
 [0.25735885]
 [0.07571838]
 [0.19124378]
 [0.34193307]
 [0.5245912 ]
 [0.72093356]
 [0.16889054]
 [0.89075786]
 [0.19133231]
 [0.08023093]
 [0.5212261 ]
 [0.5426225 ]
 [0.15026933]
 [0.11443596]
 [0.2711411 ]
 [0.13343388]
 [0.23863898]
 [0.05091142]
 [0.84286815]]

In [35]:
#step2: convert probability to 0 or 1
y_pred=(y_pred > 0.5).astype(int)
print(y_pred)

[[0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]]

In [36]:
#step3: accuracy score
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.796875

In [37]:
#step4: confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[107  12]
 [ 27  46]]